
spring:
    application:
        name: lianxi
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
#    datasource:
#      name: test
#      url:
#      username:
#      password:
#      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
    rabbitmq:
      host: ${RABBIT_MQ_HOST:localhost}
      port:  ${RABBIT_MQ_PORT:5672}
      username: guest
      password: guest
    sleuth:
      enabled: true
      http:
        legacy:
          enabled: true
#    cloud:
#      nacos:
#        discovery:
#            server-addr: 127.0.0.1:8848
#      sentinel:
#        transport:
#          dashboard: localhost:8080
mybatis:
    basepackage: com.hgshequ.springcloud.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

server:
    port: 8888 #启动端口

